Revert "feat: upgrade to latest stackage lts and ghc 9.2.5"
This reverts commit 1b0ff90fa35c112f5dff214c1394e6cd582a3a6c.

tree-diff 0.0.2.1 (last non-gpl version) fails to build:

src/Data/TreeDiff/Class.hs:298:30: error:
    Not in scope: type constructor or class ‘Semi.Option’
    Module ‘Data.Semigroup’ does not export ‘Option’.
    |
298 | instance ToExpr a => ToExpr (Semi.Option a) where
    |                              ^^^^^^^^^^^